// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ExecutionsLogging: ExecutionsStub {
    let inner: any ExecutionsStub
    let logger: Logger

    public init(_ inner: any ExecutionsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-workflows-executions-v1"
      logger[metadataKey: "gcp.client.service"] = "workflowexecutions"
      logger[metadataKey: "gcp.experimental.swift.client"] = "Executions"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listExecutions(
      request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.ListExecutionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listExecutions",
        action: {
          (r: ListExecutionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWorkflowsExecutionsV1.ListExecutionsResponse
          in
          return try await self.inner.listExecutions(request: r, options: o)
        })
    }

    public func createExecution(
      request: CreateExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      try await self._intercept(
        request: request,
        options: options,
        name: "createExecution",
        action: {
          (r: CreateExecutionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWorkflowsExecutionsV1.Execution
          in
          return try await self.inner.createExecution(request: r, options: o)
        })
    }

    public func getExecution(
      request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      try await self._intercept(
        request: request,
        options: options,
        name: "getExecution",
        action: {
          (r: GetExecutionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWorkflowsExecutionsV1.Execution
          in
          return try await self.inner.getExecution(request: r, options: o)
        })
    }

    public func cancelExecution(
      request: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelExecution",
        action: {
          (r: CancelExecutionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudWorkflowsExecutionsV1.Execution
          in
          return try await self.inner.cancelExecution(request: r, options: o)
        })
    }
  }
}
