// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol ExecutionsStub: Sendable {
    func listExecutions(
      request: ListExecutionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.ListExecutionsResponse

    func createExecution(
      request: CreateExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution

    func getExecution(
      request: GetExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution

    func cancelExecution(
      request: CancelExecutionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution
  }
}
