// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A running instance of a
/// [Workflow](/workflows/docs/reference/rest/v1/projects.locations.workflows).
public struct Execution: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the execution.
  /// Format:
  /// projects/{project}/locations/{location}/workflows/{workflow}/executions/{execution}
  public var name: Swift.String = Swift.String()

  /// Output only. Marks the beginning of execution.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Marks the end of execution, successful or not.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Measures the duration of the execution.
  public var duration: GoogleCloudWKT.Duration? = nil

  /// Output only. Current state of the execution.
  public var state: Execution.State = Execution.State()

  /// Input parameters of the execution represented as a JSON string.
  /// The size limit is 32KB.
  ///
  /// *Note*: If you are using the REST API directly to run your workflow, you
  /// must escape any JSON string value of `argument`. Example:
  /// `'{"argument":"{\"firstName\":\"FIRST\",\"lastName\":\"LAST\"}"}'`
  public var argument: Swift.String = Swift.String()

  /// Output only. Output of the execution represented as a JSON string. The
  /// value can only be present if the execution's state is `SUCCEEDED`.
  public var result: Swift.String = Swift.String()

  /// Output only. The error which caused the execution to finish prematurely.
  /// The value is only present if the execution's state is `FAILED`
  /// or `CANCELLED`.
  public var error: Execution.Error? = nil

  /// Output only. Revision of the workflow this execution is using.
  public var workflowRevisionId: Swift.String = Swift.String()

  /// The call logging level associated to this execution.
  public var callLogLevel: Execution.CallLogLevel = Execution.CallLogLevel()

  /// Output only. Status tracks the current steps and progress data of this
  /// execution.
  public var status: Execution.Status? = nil

  /// Labels associated with this execution.
  /// Labels can contain at most 64 entries. Keys and values can be no longer
  /// than 63 characters and can only contain lowercase letters, numeric
  /// characters, underscores, and dashes. Label keys must start with a letter.
  /// International characters are allowed.
  /// By default, labels are inherited from the workflow but are overridden by
  /// any labels associated with the execution.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Output only. Error regarding the state of the Execution resource. For
  /// example, this field will have error details if the execution data is
  /// unavailable due to revoked KMS key permissions.
  public var stateError: Execution.StateError? = nil

  /// Initialize a new instance of `Execution`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Execution().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A single stack element (frame) where an error occurred.
  public struct StackTraceElement: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The step the error occurred at.
    public var step: Swift.String = Swift.String()

    /// The routine where the error occurred.
    public var routine: Swift.String = Swift.String()

    /// The source position information of the stack trace element.
    public var position: Execution.StackTraceElement.Position? = nil

    /// Initialize a new instance of `StackTraceElement`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackTraceElement().with { $0.step = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Position contains source position information about the stack trace
    /// element such as line number, column number and length of the code block
    /// in bytes.
    public struct Position: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The source code line number the current instruction was generated from.
      public var line: Swift.Int64 = Swift.Int64()

      /// The source code column position (of the line) the current instruction
      /// was generated from.
      public var column: Swift.Int64 = Swift.Int64()

      /// The number of bytes of source code making up this stack trace element.
      public var length: Swift.Int64 = Swift.Int64()

      /// Initialize a new instance of `Position`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Position().with { $0.line = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.StackTraceElement.Position"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.StackTraceElement"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A collection of stack elements (frames) where an error occurred.
  public struct StackTrace: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// An array of stack elements.
    public var elements: [Execution.StackTraceElement] = []

    /// Initialize a new instance of `StackTrace`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StackTrace().with { $0.elements = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.StackTrace"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Error describes why the execution was abnormally terminated.
  public struct Error: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Error message and data returned represented as a JSON string.
    public var payload: Swift.String = Swift.String()

    /// Human-readable stack trace string.
    public var context: Swift.String = Swift.String()

    /// Stack trace with detailed information of where error was generated.
    public var stackTrace: Execution.StackTrace? = nil

    /// Initialize a new instance of `Error`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Error().with { $0.payload = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.Error"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Represents the current status of this execution.
  public struct Status: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// A list of currently executing or last executed step names for the
    /// workflow execution currently running. If the workflow has succeeded or
    /// failed, this is the last attempted or executed step. Presently, if the
    /// current step is inside a subworkflow, the list only includes that step.
    /// In the future, the list will contain items for each step in the call
    /// stack, starting with the outermost step in the `main` subworkflow, and
    /// ending with the most deeply nested step.
    public var currentSteps: [Execution.Status.Step] = []

    /// Initialize a new instance of `Status`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Status().with { $0.currentSteps = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Represents a step of the workflow this execution is running.
    public struct Step: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Name of a routine within the workflow.
      public var routine: Swift.String = Swift.String()

      /// Name of a step within the routine.
      public var step: Swift.String = Swift.String()

      /// Initialize a new instance of `Step`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Step().with { $0.routine = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.Status.Step"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.Status"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes an error related to the current state of the Execution resource.
  public struct StateError: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Provides specifics about the error.
    public var details: Swift.String = Swift.String()

    /// The type of this state error.
    public var type: Execution.StateError.Type_ = Execution.StateError.Type_()

    /// Initialize a new instance of `StateError`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StateError().with { $0.details = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Describes the possible types of a state error.
    public enum Type_: Codable, Equatable, Sendable {
      /// No type specified.
      case unspecified
      /// Caused by an issue with KMS.
      case kmsError
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .kmsError: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .kmsError: return "KMS_ERROR"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "KMS_ERROR": self = .kmsError
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .kmsError
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .kmsError: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution.StateError"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Describes the current state of the execution. More states might be added
  /// in the future.
  public enum State: Codable, Equatable, Sendable {
    /// Invalid state.
    case unspecified
    /// The execution is in progress.
    case active
    /// The execution finished successfully.
    case succeeded
    /// The execution failed with an error.
    case failed
    /// The execution was stopped intentionally.
    case cancelled
    /// Execution data is unavailable. See the `state_error` field.
    case unavailable
    /// Request has been placed in the backlog for processing at a later time.
    case queued
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .active: return 1
      case .succeeded: return 2
      case .failed: return 3
      case .cancelled: return 4
      case .unavailable: return 5
      case .queued: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .active: return "ACTIVE"
      case .succeeded: return "SUCCEEDED"
      case .failed: return "FAILED"
      case .cancelled: return "CANCELLED"
      case .unavailable: return "UNAVAILABLE"
      case .queued: return "QUEUED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ACTIVE": self = .active
      case "SUCCEEDED": self = .succeeded
      case "FAILED": self = .failed
      case "CANCELLED": self = .cancelled
      case "UNAVAILABLE": self = .unavailable
      case "QUEUED": self = .queued
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .active
      case 2: self = .succeeded
      case 3: self = .failed
      case 4: self = .cancelled
      case 5: self = .unavailable
      case 6: self = .queued
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .active: return try container.encode(1)
      case .succeeded: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .cancelled: return try container.encode(4)
      case .unavailable: return try container.encode(5)
      case .queued: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Describes the level of platform logging to apply to calls and call
  /// responses during workflow executions.
  public enum CallLogLevel: Codable, Equatable, Sendable {
    /// No call logging level specified.
    case unspecified
    /// Log all call steps within workflows, all call returns, and all exceptions
    /// raised.
    case logAllCalls
    /// Log only exceptions that are raised from call steps within workflows.
    case logErrorsOnly
    /// Explicitly log nothing.
    case logNone
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .logAllCalls: return 1
      case .logErrorsOnly: return 2
      case .logNone: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CALL_LOG_LEVEL_UNSPECIFIED"
      case .logAllCalls: return "LOG_ALL_CALLS"
      case .logErrorsOnly: return "LOG_ERRORS_ONLY"
      case .logNone: return "LOG_NONE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CallLogLevel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CALL_LOG_LEVEL_UNSPECIFIED": self = .unspecified
      case "LOG_ALL_CALLS": self = .logAllCalls
      case "LOG_ERRORS_ONLY": self = .logErrorsOnly
      case "LOG_NONE": self = .logNone
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CallLogLevel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .logAllCalls
      case 2: self = .logErrorsOnly
      case 3: self = .logNone
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .logAllCalls: return try container.encode(1)
      case .logErrorsOnly: return try container.encode(2)
      case .logNone: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workflows.executions.v1.Execution"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
