// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class ExecutionsTransport: ExecutionsStub {
    let inner: GoogleGax._HTTPClient

    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      self.inner = try GoogleGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://workflowexecutions.googleapis.com",
      )
    }

    public func listExecutions(
      request: ListExecutionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.ListExecutionsResponse {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/workflows/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/executions"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/workflows/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/workflows/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudWorkflowsExecutionsV1.ListExecutionsResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func createExecution(
      request: CreateExecutionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/workflows/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/executions"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/workflows/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/workflows/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.execution {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleCloudWorkflowsExecutionsV1.Execution.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getExecution(
      request: GetExecutionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      let (path, query, configure) = try {
        () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/workflows/"), .singleWildcard, .literal("/executions/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/workflows/"), .singleWildcard, .literal("/executions/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/workflows/*/executions/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudWorkflowsExecutionsV1.Execution.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelExecution(
      request: CancelExecutionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudWorkflowsExecutionsV1.Execution {
      let (path, query, configure, omitted) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void, [Swift.String]
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/workflows/"), .singleWildcard, .literal("/executions/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) }, ["name"])
        }
        var paths: [GoogleGax.PathMismatch] = []
        do {
          var builder = GoogleGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/workflows/"), .singleWildcard, .literal("/executions/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/workflows/*/executions/*"
          )
          paths.append(builder.build())
        }
        throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request, omitting: omitted)
      return try await req.rpc(
        GoogleCloudWorkflowsExecutionsV1.Execution.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
