// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for the
/// [ListExecutions][]
/// method.
public struct ListExecutionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of the workflow for which the executions should be listed.
  /// Format: projects/{project}/locations/{location}/workflows/{workflow}
  public var parent: Swift.String = Swift.String()

  /// Maximum number of executions to return per call.
  /// Max supported value depends on the selected Execution view: it's 1000 for
  /// BASIC and 100 for FULL. The default value used if the field is not
  /// specified is 100, regardless of the selected view. Values greater than
  /// the max value will be coerced down to it.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// A page token, received from a previous `ListExecutions` call.
  /// Provide this to retrieve the subsequent page.
  ///
  /// When paginating, all other parameters provided to `ListExecutions` must
  /// match the call that provided the page token.
  ///
  /// Note that pagination is applied to dynamic data. The list of executions
  /// returned can change between page requests.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. A view defining which fields should be filled in the returned
  /// executions. The API will default to the BASIC view.
  public var view: ExecutionView = ExecutionView()

  /// Optional. Filters applied to the [Executions.ListExecutions] results.
  /// The following fields are supported for filtering:
  /// executionID, state, startTime, endTime, duration, workflowRevisionID,
  /// stepName, and label.
  public var filter: Swift.String = Swift.String()

  /// Optional. The ordering applied to the [Executions.ListExecutions] results.
  /// By default the ordering is based on descending start time.
  /// The following fields are supported for order by:
  /// executionID, startTime, endTime, duration, state, and workflowRevisionID.
  public var orderBy: Swift.String = Swift.String()

  /// Initialize a new instance of `ListExecutionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListExecutionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.workflows.executions.v1.ListExecutionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
